# Generated by Django 5.1.1 on 2025-03-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_storedimage_features_storedimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedimage',
            name='name',
        ),
        migrations.AddField(
            model_name='storedimage',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='storedimage',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
