# Generated by Django 5.1.1 on 2025-03-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedimage',
            name='features',
        ),
        migrations.AddField(
            model_name='storedimage',
            name='name',
            field=models.CharField(default='Unnamed Image', max_length=255),
        ),
    ]
